/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grafica;

import Classi.*;
import MainCalled.GlobalGestor;
import static grafica.DisciplineDialog.gestor;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author predieric
 */
public class CorsiDialog extends javax.swing.JDialog {

    private int nRighe = 0;
    private String[] columnNames = {"Codice", "Nome", "Durata"};
    private Object[][] data = {};
    DefaultTableModel model = new DefaultTableModel(data, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column >= 1;
        }
    };
    static Gestore gestor = new GlobalGestor().gestorone;
    boolean check = false;

    /**
     * Creates new form CorsiDialog
     */
    public CorsiDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        for (Corso a : gestor.gc.visualizzaCorsi()) {

            Object[] row = {a.getCodiceCorso(), a.getNomeCorso(), a.getDurataAnni()};
            model.addRow(row);
            nRighe++;
        }
        jTable1.setModel(model);

        model.addTableModelListener((TableModelEvent e) -> {
            if (check|| e.getColumn() == TableModelEvent.ALL_COLUMNS) {
                return;
            }

            int row = e.getFirstRow();
            int col = e.getColumn();
            String changed = (String) model.getValueAt(row, col);
            try {
                check = true;

                switch (col) {
                    case 1: // Nome
                        if (changed == null || changed.trim().isEmpty() || changed.matches("\\d+")) {
                            model.setValueAt(gestor.gc.cercaCorso((String) model.getValueAt(row, 0)).getNomeCorso(), row, col);
                        } else {
                            // salva nuovo nome
                            gestor.gd.cambiaNome((String) model.getValueAt(row, 0), changed);
                        }
                        break;
                    case 2:
                        if ("".equals(changed) || !changed.matches("\\d+") || Integer.parseInt(changed) < 1) {
                            model.setValueAt(gestor.gc.cercaCorso((String) model.getValueAt(row, 0)).getDurataAnni() + "", row, col);
                        } else {
                            gestor.gc.cambiaAnni((String) model.getValueAt(row, 0), Integer.parseInt(changed));
                        }
                        break;

                }
            } finally {
                check = false;
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonInserisci = new javax.swing.JButton();
        codeInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonInserisci1 = new javax.swing.JButton();
        durataInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        salvabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonInserisci.setText("Inserisci");
        buttonInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserisciActionPerformed(evt);
            }
        });

        codeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Codice");

        buttonInserisci1.setBackground(new java.awt.Color(255, 0, 0));
        buttonInserisci1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonInserisci1.setText("EXIT");
        buttonInserisci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserisci1ActionPerformed(evt);
            }
        });

        durataInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durataInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Durata");

        nomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Nome");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Corsi");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricola Studente", "Nome", "Cognome", "Corso"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(500, 80));
        jScrollPane1.setViewportView(jTable1);

        delete.setText("Elimina");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        salvabtn.setText("Salva");
        salvabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInserisci1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(durataInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(buttonInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonInserisci1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salvabtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(durataInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserisciActionPerformed
        boolean error = false;

        String nome = nomeInput.getText();
        String durata = durataInput.getText();
        String code = codeInput.getText();

        if ("".equals(nome)) {
            error = true;
            nomeInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            nomeInput.setBorder(new JTextField().getBorder());
        }

        if ("".equals(durata) || !durata.matches(".*\\d.*")) {
            error = true;
            durataInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            durataInput.setBorder(new JTextField().getBorder());
        }

        if ("".equals(code)) {
            error = true;
            codeInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            codeInput.setBorder(new JTextField().getBorder());
        }

        if (error) {
            System.out.println("Errore nell'inserimento");
        } else {
            if (gestor.gc.creaCorso(code, nome, Integer.parseInt(durata))) {
                Object[] nuovaRiga = {code, nome, durata};
                model.addRow(nuovaRiga);
                jTable1.setRowSelectionInterval(nRighe, nRighe);
                nRighe++;
                if (model.getRowCount() > 1) {
                    delete.setBackground(Color.white);
                }
                codeInput.setBorder(new JTextField().getBorder());
                durataInput.setBorder(new JTextField().getBorder());
                nomeInput.setBorder(new JTextField().getBorder());

            } else {
                codeInput.setBorder(new LineBorder(Color.red, 3));
                durataInput.setBorder(new LineBorder(Color.red, 3));
                nomeInput.setBorder(new LineBorder(Color.red, 3));
            }
        }
        // new Studente(string matricola, string nome, string cognome, corso corsoiscritto)
    }//GEN-LAST:event_buttonInserisciActionPerformed

    private void codeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeInputActionPerformed

    private void buttonInserisci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserisci1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonInserisci1ActionPerformed

    private void durataInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durataInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durataInputActionPerformed

    private void nomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeInputActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int[] rowsSelected = jTable1.getSelectedRows();
        if (model.getRowCount() > 1 && model.getRowCount() > rowsSelected.length) {

            for (int i = rowsSelected.length; i > 0; i--) {
                String code = (String) model.getValueAt(i, 0);
                System.out.println(code);
                gestor.gc.elimina(code);
                model.removeRow(i);
                nRighe--;
            }
            delete.setBackground(Color.white);
        } else
            delete.setBackground(Color.red);
    }//GEN-LAST:event_deleteActionPerformed

    private void salvabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvabtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> csv = new ArrayList<>();
        for (Corso i : gestor.gc.visualizzaCorsi()) {
            csv.add(i.toString());
        }
        gestor.gl.writeFile("corsi.csv", csv);

    }//GEN-LAST:event_salvabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorsiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorsiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorsiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorsiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CorsiDialog dialog = new CorsiDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInserisci;
    private javax.swing.JButton buttonInserisci1;
    private javax.swing.JTextField codeInput;
    private javax.swing.JButton delete;
    private javax.swing.JTextField durataInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JButton salvabtn;
    // End of variables declaration//GEN-END:variables
}
