/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grafica;

import Classi.*;
import MainCalled.GlobalGestor;
import static grafica.StudentiDialog.gestor;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author predieric
 */
public class DocentiDialog extends javax.swing.JDialog {

    private int nRighe = 0;
    private String[] columnNames = {"Matricola", "Nome", "Cognome", "Disciplina"};
    private Object[][] data = {};
    DefaultTableModel model = new DefaultTableModel(data, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column >= 1;  // tutte le celle diventano non modificabili
        }
    };
    static Gestore gestor = new GlobalGestor().gestorone;
    boolean check = false;

    /**
     * Creates new form DocentiDialog
     */
    public DocentiDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (Docente a : gestor.gdoc.visualizzaDocenti()) {

            Object[] row = {a.getMatricolaDocente(), a.getNome(), a.getCognome(), a.getDisciplinaDocente().getNomeDisciplina()};
            model.addRow(row);
            nRighe++;
        }
        jTable1.setModel(model);
        ArrayList<String> boxModel = new ArrayList<>();
        boxModel.add("");
        for (Disciplina c : gestor.gd.visualizzaDiscipline()) {
            boxModel.add(c.getNomeDisciplina());
        }

        String[] comboBoxModel = boxModel.toArray(new String[0]);
        disciplinaBox.setModel(new DefaultComboBoxModel<>(comboBoxModel));
        boxModel.remove(0);
        String[] boxModelChange = boxModel.toArray(new String[0]);
        JComboBox<String> comboBox = new JComboBox<>(boxModelChange);

        TableColumn colonna = jTable1.getColumnModel().getColumn(3);
        colonna.setCellEditor(new DefaultCellEditor(comboBox));

        model.addTableModelListener((TableModelEvent e) -> {
            if (check || e.getColumn() == TableModelEvent.ALL_COLUMNS) {
                return;
            }

            int row = e.getFirstRow();
            int col = e.getColumn();
            String changed = (String) model.getValueAt(row, col);
            try {
                check = true;

                switch (col) {
                    case 1: // Nome
                        if (changed == null || changed.trim().isEmpty() || changed.matches("\\d+")) {
                            model.setValueAt(gestor.gdoc.cercaDocente((String) model.getValueAt(row, 0)).getNome(), row, col);
                        } else {
                            // salva nuovo nome
                            gestor.gdoc.cambiaNome((String) model.getValueAt(row, 0), changed);
                        }
                        break;
                    case 2: // CFU
                        if (changed == null || changed.trim().isEmpty() || changed.matches("\\d+")) {
                            model.setValueAt(gestor.gdoc.cercaDocente((String) model.getValueAt(row, 0)).getCognome(), row, col);
                        } else {
                            // salva nuovo nome
                            gestor.gdoc.cambiaCognome((String) model.getValueAt(row, 0), changed);
                        }
                        break;
                    case 3:
                        String selected = (String) comboBox.getSelectedItem();
                        System.out.println(selected);
                        gestor.gdoc.cambiaDisciplina((String) model.getValueAt(row, 0), gestor.gd.cercaDisciplinaNome(selected));
                        break;
                }
            } finally {
                check = false;
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        matricolaInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cognomeInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonInserisci1 = new javax.swing.JButton();
        buttonInserisci = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        delete1 = new javax.swing.JButton();
        disciplinaBox = new javax.swing.JComboBox<>();
        salvabtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Docenti");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Matricola  ");

        matricolaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricolaInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Nome");

        nomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Cognome");

        cognomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cognomeInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Disciplina");

        buttonInserisci1.setBackground(new java.awt.Color(255, 0, 0));
        buttonInserisci1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonInserisci1.setText("EXIT");
        buttonInserisci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserisci1ActionPerformed(evt);
            }
        });

        buttonInserisci.setText("Inserisci");
        buttonInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserisciActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricola Studente", "Nome", "Cognome", "Corso"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(500, 80));
        jScrollPane1.setViewportView(jTable1);

        delete1.setText("Elimina");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        disciplinaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salvabtn1.setText("Salva");
        salvabtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvabtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(matricolaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cognomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(disciplinaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(buttonInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(salvabtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInserisci1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvabtn1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(buttonInserisci1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cognomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(disciplinaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matricolaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(delete1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonInserisci)
                        .addGap(27, 27, 27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricolaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricolaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricolaInputActionPerformed

    private void nomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeInputActionPerformed

    private void cognomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cognomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cognomeInputActionPerformed

    private void buttonInserisci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserisci1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonInserisci1ActionPerformed

    private void buttonInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserisciActionPerformed
        boolean error = false;
        String matricola = matricolaInput.getText();
        String nome = nomeInput.getText();
        String cognome = cognomeInput.getText();
        String disciplina = (String) disciplinaBox.getSelectedItem();

        if ("".equals(matricola)) {
            error = true;
            matricolaInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            matricolaInput.setBorder(new JTextField().getBorder());
        }

        if ("".equals(nome)) {
            error = true;
            nomeInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            nomeInput.setBorder(new JTextField().getBorder());
        }

        if ("".equals(cognome)) {
            error = true;
            cognomeInput.setBorder(new LineBorder(Color.red, 3));
        } else {
            cognomeInput.setBorder(new JTextField().getBorder());
        }

        if ("".equals(disciplina)) {
            error = true;
            disciplinaBox.setBorder(new LineBorder(Color.red, 3));
        } else {
            disciplinaBox.setBorder(new JComboBox().getBorder());
        }

        if (error) {
            System.out.println("Errore nell'inserimento");
        } else {
            if (gestor.gdoc.inserisciDocente(matricola, nome, cognome, gestor.gd.cercaDisciplinaNome(disciplina))) {
                Object[] nuovaRiga = {matricola, nome, cognome, disciplina};
                model.addRow(nuovaRiga);
                jTable1.setRowSelectionInterval(nRighe, nRighe);
                nRighe++;

                if (model.getRowCount() > 1) {
                    delete1.setBackground(Color.white);
                }
                matricolaInput.setBorder(new JTextField().getBorder());
                nomeInput.setBorder(new JTextField().getBorder());
                cognomeInput.setBorder(new JTextField().getBorder());
                disciplinaBox.setBorder(new JComboBox().getBorder());

            } else {
                nomeInput.setBorder(new LineBorder(Color.red, 3));
                matricolaInput.setBorder(new LineBorder(Color.red, 3));
                cognomeInput.setBorder(new LineBorder(Color.red, 3));
                disciplinaBox.setBorder(new LineBorder(Color.red, 3));
            }

        }
        // new Studente(string matricola, string nome, string cognome, corso corsoiscritto)
    }//GEN-LAST:event_buttonInserisciActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        int[] selectedRows = jTable1.getSelectedRows();

        if (selectedRows.length == 0) {
            delete1.setBackground(Color.red);

        }
        if (model.getRowCount() > 1 && model.getRowCount() > selectedRows.length) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                int row = selectedRows[i];
                String code = (String) model.getValueAt(row, 0);
                gestor.gdoc.elimina(code);
                model.removeRow(row);
                nRighe--;
            }delete1.setBackground(Color.white);
        } else delete1.setBackground(Color.red);
        
    }//GEN-LAST:event_delete1ActionPerformed

    private void salvabtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvabtn1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> csv = new ArrayList<>();
        for (Docente i : gestor.gdoc.visualizzaDocenti()) {
            csv.add(i.toString());
        }
        gestor.gl.writeFile("docenti.csv", csv);
    }//GEN-LAST:event_salvabtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocentiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocentiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocentiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocentiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DocentiDialog dialog = new DocentiDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInserisci;
    private javax.swing.JButton buttonInserisci1;
    private javax.swing.JTextField cognomeInput;
    private javax.swing.JButton delete1;
    private javax.swing.JComboBox<String> disciplinaBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField matricolaInput;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JButton salvabtn1;
    // End of variables declaration//GEN-END:variables
}
